kind: Deployment
apiVersion: apps/v1
metadata:
  name: users-app
  namespace: testing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-app
  template:
    metadata:
      labels:
        app: users-app
    spec:
      containers:
        - name: users-app
          image: 'users-service:v0.1'
          ports:
            - containerPort: 3000