apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: users-app-hpa
  namespace: testing
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: users-app
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
