apiVersion: v1
kind: Service
metadata:
  name: users-app-service
  namespace: testing
  labels:
    app: users-app
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: 3000
  selector:
    app: users-app