apiVersion: v1
kind: Service
metadata:
  name: posts-app-service
  namespace: testing
  labels:
    app: post-app
spec: 
  type: ClusterIP
  ports:
    - port: 5100
      targetPort: 3000
  selector:
    app: post-app